name: Run tests

on:
  push:
    branches:
      - '*'
permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none
  
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20.10.0'

      - name: Install dependencies
        run: yarn install

      - name: Install cypress
        run: yarn cypress install

      - name: Run tests
        run: yarn dev

      - name: Run tests
        run: yarn cy:run
